### ISSUE TITLE
Display diff of html instead of data structure?

### ISSUE THREAD

**Issue by mccalluc** [JamesMGreene/qunit-assert-html#5]
Not sure if this something you'd want, but if the comparison fails, I find it easier to look at a diff of the HTML rather than of the JSON serialization. There could be other junk in the diff, which you have normalized out, but the real problem is in there, too, and probably easier to spot?

```diff
Index: qunit-assert-html-0.2.0.js
===================================================================
--- qunit-assert-html-0.2.0.js	(revision 3335)
+++ qunit-assert-html-0.2.0.js	(working copy)
@@ -346,7 +346,7 @@
 				message = "HTML should be equal";
 			}
 
-			this.deepEqual( serializeHtml( actual ), serializeHtml( expected ), message );
+			QUnit.push( QUnit.equiv( serializeHtml( actual ), serializeHtml( expected ) ), actual, expected, message );
 		},
 
 		/**
@@ -362,7 +362,7 @@
 				message = "HTML should not be equal";
 			}
 
-			this.notDeepEqual( serializeHtml( actual ), serializeHtml( expected ), message );
+			QUnit.push( !QUnit.equiv( serializeHtml( actual ), serializeHtml( expected ) ), actual, expected, message );
 		},
 
 		/**
```

**Comment by JamesMGreene** [comment]
So I implemented something similar but beyond this and released it in `v1.1.0`.

I basically added some machinery to convert the normalized data structures back into HTML and that is what's now displayed.  It's still not the best as this often includes superfluous `style` values (e.g. `display: inline; width: auto; height: auto;` on most of my unit tests) but it's definitely more easily interpreted by the consumer than the data structures.

It can also be potentially a bit confusing since I am now showing the normalized HTML rather than the original HTML, which makes it possibly harder to track back to its origin in the tests but should make it much easier to view the perceived differences (or lack thereof) that caused the assertion failure.
